### ISSUE TITLE
Coverage.py concurrency tests get stuck on windows 7.3.15, didn't on 7.3.14

### ISSUE THREAD

**Issue by nedbat** [pypy/pypy#4876] opened 2024-01-23 14:20 UTC
Sorry for the difficult issue report... The coverage.py test suite is getting stuck when running on Windows PyPy 7.3.15, when it didn't on 7.3.14.  We've narrowed down the tests to tests/test_concurrency.py, but it's difficult to debug further.  The details that we have are in the coverage.py issue: https://github.com/nedbat/coveragepy/issues/1737

I'm hoping a PyPy dev might have ideas of what could have changed, or have some skillz to use debugging it.

**Comment by devdanzin** [comment] 2024-01-24 12:28
Here's a standalone reproducer without coverage. Just run it in a PyPy virtual environment.

```python
import multiprocessing as mp
import sys

def worker(a):
    print(sys.executable, "worker python")

if __name__ == "__main__":
    print(sys.executable, "main python")
    mp.set_start_method("spawn")
    p = mp.Pool(3)
    outputs = p.imap_unordered(worker, [(x,) for x in range(6)])
    p.close()
    p.join()
```

**Comment by mattip** [comment] 2024-01-24 14:52
@nulano could you take a look?

**Comment by nulano** [comment] 2024-01-24 16:49
Looks like this is caused by [bpo-35797](https://bugs.python.org/issue35797).
AFAIU, venv pypy.exe is not a launcher executable that just runs the system python executable unlike CPython, so that change needs to be disabled on PyPy.

Disabling this if block fixes the snippet above (https://github.com/pypy/pypy/issues/4876#issuecomment-1908030550) for me:
https://github.com/pypy/pypy/blob/aed579895e540042a8a3bd80072529c4ad4a4dac/lib-python/3/multiprocessing/popen_spawn_win32.py#L63-L66

**Comment by mattip** [comment] 2024-04-17 11:14
I added the suggested fix in #4893, but the test from this issue [is failing](https://buildbot.pypy.org/summary/longrepr?testname=test_multiprocessing&builder=pypy-c-jit-win-x86-64&build=1667&mod=test_venv).

**Comment by nulano** [comment] 2024-04-17 19:31
Two observations:

1. > returned non-zero exit status 3221225781

   That is C0000135 in hex, i.e. STATUS_DLL_NOT_FOUND, so there seems to be something wrong with the venv.
   Perhaps `libpypy3.9-c.dll` did not get copied properly?

2. When I run the test using the nightly build, it passes:

```
C:\Users\Nulano\Downloads\pypy-c-jit-183847-ebdd501f7ec8-win64>pypy3.exe -mpytest C:\Git\pypy_git\extra_tests\test_venv.py
================================================= test session starts =================================================
platform win32 -- Python 3.9.19[pypy-7.3.16-alpha], pytest-8.1.1, pluggy-1.4.0
rootdir: C:\Git\pypy_git\extra_tests
configfile: pytest.ini
collected 2 items

..\..\..\..\Git\pypy_git\extra_tests\test_venv.py ..                                                             [100%]

================================================= 2 passed in 18.52s ==================================================
```

   For comparison, a previous nightly build fails the test:

```
C:\Users\Nulano\Downloads\pypy-c-jit-183835-15645aff62cb-win64>pypy3.exe -mpytest -v C:\Git\pypy_git\extra_tests\test_venv.py
============================================================================================================================ test session starts ============================================================================================================================
platform win32 -- Python 3.9.19[pypy-7.3.16-alpha], pytest-8.1.1, pluggy-1.4.0 -- C:\Users\Nulano\Downloads\pypy-c-jit-183835-15645aff62cb-win64\pypy3.exe
cachedir: .pytest_cache
rootdir: C:\Git\pypy_git\extra_tests
configfile: pytest.ini
collected 2 items

..\..\..\..\Git\pypy_git\extra_tests\test_venv.py::test_venv_of_venv PASSED                                                                                                                                                                                            [ 50%]
..\..\..\..\Git\pypy_git\extra_tests\test_venv.py::test_multiprocessing FAILED                                                                                                                                                                                         [100%]

================================================================================================================================= FAILURES ==================================================================================================================================
___________________________________________________________________________________________________________________________ test_multiprocessing ____________________________________________________________________________________________________________________________

tmpdir = local('C:\\Users\\Nulano\\AppData\\Local\\Temp\\pytest-of-Nulano\\pytest-86\\test_multiprocessing0')

    def test_multiprocessing(tmpdir):
        # issue 4876
        subprocess.run([sys.executable, '-mvenv', str(tmpdir / 'venv')])
        # 'bin' or 'Script'
        path = os.path.split(sysconfig.get_path('scripts'))[-1]
        exe = str(tmpdir / 'venv' / path / os.path.split(sys.executable)[-1])
        result = subprocess.run([exe, '-c',
                                 'from multiprocessing import Pool; ' +
                                 'print(Pool(1).apply_async(eval, ("__import__(\'sys\').executable",)).get(3))'],
                                capture_output=True)
        result.check_returncode()
>       assert result.stdout.strip() == exe.encode()
E       AssertionError: assert b'C:\\Users\\...64\\pypy3.exe' == b'C:\\Users\\...ts\\pypy3.exe'
E
E         At index 16 diff: b'D' != b'A'
E
E         Full diff:
E         - (b'C:\\Users\\Nulano\\AppData\\Local\\Temp\\pytest-of-Nulano\\pytest-86\\test_m'
E         -  b'ultiprocessing0\\venv\\Scripts\\pypy3.exe')
E         + (b'C:\\Users\\Nulano\\Downloads\\pypy-c-jit-183835-15645aff62cb-win64\\pypy3'
E         +  b'.exe')

C:\Git\pypy_git\extra_tests\test_venv.py:26: AssertionError
========================================================================================================================== short test summary info ==========================================================================================================================
FAILED ..\..\..\..\Git\pypy_git\extra_tests\test_venv.py::test_multiprocessing - AssertionError: assert b'C:\\Users\\...64\\pypy3.exe' == b'C:\\Users\\...ts\\pypy3.exe'
======================================================================================================================= 1 failed, 1 passed in 18.26s ========================================================================================================================
```

**Comment by mattip** [comment] 2024-04-19 02:33
I wonder if this is because the test is already running in a venv, so it is creating a venv of a venv and not properly copying the libpypy dll.

**Comment by nulano** [comment] 2024-04-19 07:06
I think it's specific to how it's run on the buildbot, since creating even several nested venvs and then running the test works for me.

**Comment by mattip** [comment] 2024-04-21 05:41
@nedbat could you test a nightly?

**Comment by nedbat** [comment] 2024-04-26 12:48
I am only running this on GitHub Actions.  They aren't yet shipping 7.3.16.  I can try a nightlies run as a one-time special case.

**Comment by nedbat** [comment] 2024-04-26 12:55
Looks good: 3.9 and 3.10 passed with 7.3.17 alpha:  https://github.com/nedbat/coveragepy/actions/runs/8848522648/job/24298516597

**Comment by nedbat** [comment] 2024-04-26 15:58
.. and I am adding a PyPy Windows nightly to my test matrix.

**Comment by mattip** [comment] 2024-05-05 23:45
Thanks for the original report and checking the fix. Closing.

**Closed by mattip** 2024-05-05 23:45 UTC
Labels: windows
