### ISSUE TITLE
Unable to recognize non-English characters and unable to load large-volume files using pickle.

### ISSUE THREAD

**Issue by 5igm** [pypy/pypy#4948] opened 2024-05-14 08:05 UTC
In recent versions (possibly after 3.6 or 3.8), I've encountered a persistent issue with PyPy, which is its inability to recognize non-English languages. Even when adding a declaration like '# coding:utf-8' at the beginning of the program, it doesn't work. Not only are non-English characters within the program unrecognized, but also if there are non-English characters in the program's name itself, PyPy fails to execute. Additionally, I've noticed a significant slowdown in loading large files, such as those larger than 1GB, when using pickle with PyPy compared to Python. If you could provide any solutions to the above issues, I would be extremely grateful.

**Comment by devdanzin** [comment] 2024-05-14 10:06
Thank you for the report!

What are you doing (reading a file, running a script etc.) when the error happens? What is the error message? Can you provide a (small) sample file that causes the error, with instructions to reproduce it?

Can you paste the output of running the following code on your PyPy and Python environments?

```python
import locale, os, sys

print(f"{sys.implementation.name} {sys.platform} {sys.version}")
print(f"{os.device_encoding(0)=}")
print(f"{os.device_encoding(1)=}")
print(f"{sys.getdefaultencoding()=}")
print(f"{sys.getfilesystemencoding()=}")
print(f"{locale.getpreferredencoding()=}")
if hasattr(locale, "getencoding"):
    print(f"{locale.getencoding()=}")
print(f"{locale.getlocale()=}")
locale.setlocale(locale.LC_ALL, '')
print(f"{locale.getlocale()=}")
```

**Comment by 5igm** [comment] 2024-05-15 16:26
a sample.

**Comment by 5igm** [comment] 2024-05-15 17:35
> Thank you for the report!
> 
> What are you doing (reading a file, running a script etc.) when the error happens? What is the error message? Can you provide a (small) sample file that causes the error, with instructions to reproduce it?
> 
> Can you paste the output of running the following code on your PyPy and Python environments?
> 
> ```python
> import locale, os, sys
> 
> print(f"{sys.implementation.name} {sys.platform} {sys.version}")
> print(f"{os.device_encoding(0)=}")
> print(f"{os.device_encoding(1)=}")
> print(f"{sys.getdefaultencoding()=}")
> print(f"{sys.getfilesystemencoding()=}")
> print(f"{locale.getpreferredencoding()=}")
> if hasattr(locale, "getencoding"):
>     print(f"{locale.getencoding()=}")
> print(f"{locale.getlocale()=}")
> locale.setlocale(locale.LC_ALL, '')
> print(f"{locale.getlocale()=}")
> ```

A sample for Pypy
```
C:\Users\Jinlin Chen>pypy3
Python 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
[PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import sys
>>>> sys.stdout.encoding
'utf-8'
>>>> print('你好'.encode('utf-8').decode(sys.stdout.encoding))
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc4' in position 7: surrogates not allowed
>>>> print('你好')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc4' in position 7: surrogates not allowed
>>>>
```
Input for Python and Pypy:
```
print(f"{sys.implementation.name} {sys.platform} {sys.version}")
print(f"{os.device_encoding(0)=}")
print(f"{os.device_encoding(1)=}")
print(f"{sys.getdefaultencoding()=}")
print(f"{sys.getfilesystemencoding()=}")
print(f"{locale.getpreferredencoding()=}")
if hasattr(locale, "getencoding"):
    print(f"{locale.getencoding()=}")
print(f"{locale.getlocale()=}")
locale.setlocale(locale.LC_ALL, '')
print(f"{locale.getlocale()=}")
os.chdir(r'D:\python\works\project6')
print('file size:',os.path.getsize('input-data_2024-05-14_8154.pkl'))
start=time.time()
with open('input-data_2024-05-14_8154.pkl','rb') as file:
    input_data = pickle.load(file)
print('loading timing:',time.time()-start)
```
Output for Python:
```
cpython win32 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
os.device_encoding(0)=None
os.device_encoding(1)=None
sys.getdefaultencoding()='utf-8'
sys.getfilesystemencoding()='utf-8'
locale.getpreferredencoding()='cp936'
locale.getencoding()='cp936'
locale.getlocale()=('Chinese (Simplified)_China', '936')
locale.getlocale()=('Chinese (Simplified)_China', '936')
file size: 6630501745
loading timing: 283.23285126686096
```
Output for Pypy:
```
pypy win32 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
[PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)]
os.device_encoding(0)=None
os.device_encoding(1)=None
sys.getdefaultencoding()='utf-8'
sys.getfilesystemencoding()='utf-8'
locale.getpreferredencoding()='UTF-8'
locale.getlocale()=(None, None)
locale.getlocale()=('Chinese (Simplified)_China', '936')
file size: 6630501745
loading timing: 1203.6490168571472
```

**Comment by devdanzin** [comment] 2024-05-16 11:08
I get different results with the same PyPy version:

```
Python 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
[PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>> import sys
>>>> sys.stdout.encoding
'utf-8'
>>>> print('你好'.encode('utf-8').decode(sys.stdout.encoding))
??
>>>> print('你好')
??
```

```
pypy win32 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
[PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)]
os.device_encoding(0)='cp850'
os.device_encoding(1)='cp850'
sys.getdefaultencoding()='utf-8'
sys.getfilesystemencoding()='utf-8'
locale.getpreferredencoding()='UTF-8'
locale.getlocale()=(None, None)
locale.getlocale()=('pt_BR', 'cp1252')
```

The main differences are that `os.device_encoding(0)` is `None` for you and that `print('你好')` results in a bad `??` for me, instead of an error. 

What solves the issue for me is changing the encoding of the terminal. If you're using PowerShell, try these commands:

```powershell
[Console]::InputEncoding = New-Object System.Text.UTF8Encoding
[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

If you are on a terminal that isn't PowerShell, try:
```
chcp 65001
```

Then try your `print()` example again. This is just a workaround, PyPy still needs fixing to match CPython's behavior.

I can reproduce the issue with filenames, with a file named `你好.py` CPython will run the script, while PyPy will fail with `can't open file ??.py: [Errno 22] Invalid argument`.

Regarding pickle performance, there are some issues about it, like #1423 and #1070. I'll try to at least pinpoint what part is slower in PyPy.

**Comment by mattip** [comment] 2024-05-16 12:32
Note this problem is more acute on windows. See #3890 which is tracking some of this.

**Comment by 5igm** [comment] 2024-05-18 22:29
> I get different results with the same PyPy version:
> 
> ```
> Python 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
> [PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>> import sys
> >>>> sys.stdout.encoding
> 'utf-8'
> >>>> print('你好'.encode('utf-8').decode(sys.stdout.encoding))
> ??
> >>>> print('你好')
> ??
> ```
> 
> ```
> pypy win32 3.9.17 (3f3f2298ddc56db44bbdb4551ce992d8e9401646, Jun 15 2023, 12:06:27)
> [PyPy 7.3.12 with MSC v.1929 64 bit (AMD64)]
> os.device_encoding(0)='cp850'
> os.device_encoding(1)='cp850'
> sys.getdefaultencoding()='utf-8'
> sys.getfilesystemencoding()='utf-8'
> locale.getpreferredencoding()='UTF-8'
> locale.getlocale()=(None, None)
> locale.getlocale()=('pt_BR', 'cp1252')
> ```
> 
> The main differences are that `os.device_encoding(0)` is `None` for you and that `print('你好')` results in a bad `??` for me, instead of an error.
> 
> What solves the issue for me is changing the encoding of the terminal. If you're using PowerShell, try these commands:
> 
> ```powershell
> [Console]::InputEncoding = New-Object System.Text.UTF8Encoding
> [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding
> ```
> 
> If you are on a terminal that isn't PowerShell, try:
> 
> ```
> chcp 65001
> ```
> 
> Then try your `print()` example again. This is just a workaround, PyPy still needs fixing to match CPython's behavior.
> 
> I can reproduce the issue with filenames, with a file named `你好.py` CPython will run the script, while PyPy will fail with `can't open file ??.py: [Errno 22] Invalid argument`. This seems to be the same issue as #4924.
> 
> Regarding pickle performance, there are some issues about it, like #1423 and #1070. I'll try to at least pinpoint what part is slower in PyPy.

Normally, I don't use cmd to execute PyPy. For another example,
show in python:
```
计算数据中...
2024-03-20 13:15:00 --- 2024-04-18 10:30:00 stock_indexes_15min calc1 Sun May 19 06:28:04 2024
2024-04-18 10:45:00 --- 2024-05-17 15:00:00 stock_indexes_15min calc2 Sun May 19 06:28:05 2024
```

show in PyPy
```
璁＄畻鏁版嵁涓?..
2024-03-20 13:15:00 --- 2024-04-18 10:30:00 stock_indexes_15min calc1 Sun May 19 06:27:53 2024
2024-04-18 10:45:00 --- 2024-05-17 15:00:00 stock_indexes_15min calc2 Sun May 19 06:27:55 2024
```

**Comment by mattip** [comment] 2024-12-31 07:19
> When non-English characters are displayed by PyPy, it seems unable to render them correctly.

I think this is the important part, and is a duplicate of other repl-windows issues #3767 and #3641. Closing as a duplicate. Please reopen if I misunderstood.

**Closed by mattip** 2024-12-31 07:19 UTC
Labels: windows
