### ISSUE TITLE
`ndbm.dbm` segfaults on GC collection

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#5115] opened 2024-11-12 13:03 UTC
It's possible to segfault PyPy by deleting a `dbm.ndbm.dbm` object then calling `gc.collect`:

```
[PyPy 7.3.17 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import dbm.ndbm as n
>>>> a = n.dbm(1, 1)
>>>> del a
>>>> import gc
>>>> gc.collect()
Segmentation fault (core dumped)
```

Found using fusil by @vstinner.

**Comment by mattip** [comment] 2024-11-13 07:55
Thanks for the report. `dbm.ndbm.dbm` is not supposed to be exposed. Fixed in c1b68d59

**Closed** 2024-11-13 07:56 UTC

**Comment by devdanzin** [comment] 2024-11-15 21:40
I got another crash on the nightly with `_dbm.dbm(b"\x00" 10, 1); gc.collect()`, is it the same issue?

**Comment by mattip** [comment] 2024-11-16 16:14
On CPython _dbm.dbm does not exist. On PyPy, it is accessible but after c1b68d5 is no longer part of `__all__`. I don't know if we can idiot-proof this entirely, but I did d0c1d7ffa4e which changes the name of the class to `_dbm` and also tries to ensure `close` is not called without `open` (the root cause of this issue: the first argument to `_dbm()` is meant to be a valid open dbm database).
