### ISSUE TITLE
PyPy is missing attributes in "stat" module

### ISSUE THREAD

**Issue by Erotemic** [pypy/pypy#4953] opened 2024-05-16 16:45 UTC
Initial discussion is here: https://github.com/orgs/pypy/discussions/4952

The issue is that on windows the `stat` module should define:

* IO_REPARSE_TAG_APPEXECLINK
* IO_REPARSE_TAG_MOUNT_POINT
* IO_REPARSE_TAG_SYMLINK

but these are missing.

**Comment by mattip** [comment] 2024-05-16 19:11
Added in 1f46a199917. If the issue is causing you problems, you can modify the local version of stat.py and add the constants like in the changeset. 

Closing, thanks for the report. Please reopen if I missed something.

**Closed by mattip** 2024-05-16 19:11 UTC

**Comment by Erotemic** [comment] 2024-05-16 20:57
Will this be in a patch release of pypy 3.9? The issue is that the stdlib `shutil.copytree` itself is broken on win32 when these attributes are not present and the copied directory contains a symlink. I find it surprising that there isn't a test case for that, but it is somewhat specific. I'd prefer not to monkey patch the stats module if possible, as this is an issue with a library not a particular application.

**Comment by mattip** [comment] 2024-05-17 05:53
There are nightly builds, they can be used in github CI via [the nightly tag](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#specifying-a-pypy-version) or can be downloaded from https://buildbot.pypy.org/nightly/
