### ISSUE TITLE
SSL Error: Unable to Connect to HTTPS URL for PyPy-3.10-nightly version on Windows

### ISSUE THREAD

**Issue by aparnajyothi-y** [pypy/pypy#5074] opened 2024-10-10 07:09 UTC
Facing SSL Error: Unable to Connect to HTTPS URL for PyPy-3.10-nightly version on Windows -2022 and please find the [failure links](https://github.com/actions/setup-python/actions/runs/11098960252/job/30832442213) for reference.
Reference of closed https://github.com/pypi/warehouse/issues/16802
**How to Reproduce**
```
jobs:
setup-pypy:
name: Setup PyPy ${{ matrix.pypy }} ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os: [windows-latest]
pypy:
- 'pypy-3.10-nightly'

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: setup-python ${{ matrix.pypy }}
    id: setup-python
    uses: ./
    with:
      python-version: ${{ matrix.pypy }}
```
**Output**
```
Error we are getting is mentioned below
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
The process 'D:\a_temp\5871[35](https://github.com/actions/setup-python/actions/runs/10957214111/job/30424936558?pr=947#step:3:36)78-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1
Error: The process 'D:\a_temp\58713578-6f7f-47f8-a4ec-62dcdc704c0d\pypy-c-jit-185389-9ca9d9be1715-win64\python.exe' failed with exit code 1
```

**Comment by mattip** [comment] 2024-10-10 07:41
Thanks. I noticed this also and think I have a fix. The problem is this 
> the ssl module in Python is not available

which is a result of not being able to import `_ssl`, which seems to be a bad merge from `main` removing needed flags when `dlopen`ing an extension module.

**Comment by mattip** [comment] 2024-10-10 08:36
Should be fixed by  6714cb35da.

**Comment by aparnajyothi-y** [comment] 2024-10-11 07:26
Hello @mattip,Thank you for the fix! Could you please let us know when we can expect a release that includes this fix?

**Comment by mattip** [comment] 2024-10-11 07:52
The problem occurs on the "nightly" builds. A newer nightly with the fix is already available. Can you kick off a CI run to test it?

**Comment by mattip** [comment] 2024-10-30 15:26
Closing as "fixed"

**Closed by mattip** 2024-10-30 15:26 UTC
