### ISSUE TITLE
Pickle.dumps()'s results are different.

### ISSUE THREAD

**Issue by zzl261004** [pypy/pypy#5011] opened 2024-08-27 14:37 UTC
The results of pypy --jit off and pypy --jit threshold=1 are different.  The following test.py is my minimized program.

test.py
```
import pickle
options=['ab','ab','ab','ab','ab','ab','ab','ab']
temp = []
for i in options:
    args = []
    args.append('' + i)
    temp += args

#The results of pypy --jit off and pypy --jit threshold=1 are different.
data_bytes = pickle.dumps(temp)

print(data_bytes)
```

pypy with JIT disabled:  (  pypy --jit off test.py  )
```
b'\x80\x04\x95-\x00\x00\x00\x00\x00\x00\x00]\x94(\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94e.'
```

With threshold=1 set in PyPy:  (  pypy --jit threshold=1 test.py  )
```
b'\x80\x04\x95$\x00\x00\x00\x00\x00\x00\x00]\x94(\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94\x8c\x02ab\x94h\x04h\x04h\x04e.'
```

Environment:
Python 3.9.19 (a2113ea87262, Apr 21 2024, 05:40:24)
[PyPy 7.3.16 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Operating System: Ubuntu 22.04.4 LTS

**Comment by cfbolz** [comment] 2024-08-28 15:35
yeah, I can reproduce this. pretty weird (note however that *unpickling* this will give you the same string back in both cases).

**Comment by cfbolz** [comment] 2024-08-28 16:08
right, I see. the JIT will constant-fold the `'' + 'ab'` to a constant string in the loop, which leads pickle to re-use the object reference instead of serializing the string again. this effect can be observed with this code too:

```python
options=['ab','ab','ab','ab','ab','ab','ab','ab'] * 10000
temp = []
for i in options:
    print(id('' + i))
```

at some point, the id will become stable, because after the JIT has generated code for the loop the addition returns always the same string object. A lot of coincidences have to come together to cause this effect, eg if you put it into a function instead of running the code on the global level the constant-folding doesn't happen any more.

Because the unpickled list is the same, I don't consider this a real bug and more of a corner case.

@zzl261004 could you give some more details about why this was a problem for you, in the context of the larger program you were running?

Background thoughts: Combining identity with immutable data types is always a bit of a problem. It would be really costly to get rid of all of these corner cases in PyPy, and CPython changes them too, from time to time. It's of course unfortunate that pickle makes the `id` visible under some circumstances. Some examples for weirdness around `id` in CPython are whether the two numbers that the following program prints are the same or different depends on the CPython version:

```python
print(id('a' * 100 + 'b'), id('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'))
```

or the weirdness of this cpython-behaviour:

```python
>>> def f(x): return x - 1 + 1 is x
... 
>>> f(100)
True
>>> f(1000)
False
```

(both returns true in pypy for arbitrary arguments.)

**Comment by mattip** [comment] 2024-08-29 06:03
I don't think there is any guarantee that `pickle()` will always give an identical binary serialization. As long as the `loads()` gives the correct reconstruction on both CPython and PyPY, I think that is sufficient.

**Comment by zzl261004** [comment] 2024-09-01 05:09
> 是的，我明白了。JIT 将在循环中将常量折叠`'' + 'ab'`为常量字符串，这导致 pickle 重新使用对象引用而不是再次序列化字符串。此代码也可以观察到此效果：
> 
> ```python
> options=['ab','ab','ab','ab','ab','ab','ab','ab'] * 10000
> temp = []
> for i in options:
>     print(id('' + i))
> ```
> 
> 在某个时候，id 将变得稳定，因为在 JIT 为循环生成代码后，加法总是返回相同的字符串对象。许多巧合必须结合在一起才能产生这种效果，例如，如果您将其放入函数中而不是在全局级别运行代码，则常量折叠不会再发生。
> 
> 因为未解压的列表是相同的，所以我不认为这是一个真正的错误，而更像是一个极端情况。
> 
> @zzl261004在您正在运行的更大的程序的背景下，您能否提供一些关于为什么这对您来说是一个问题的详细信息？
> 
> 背景想法：将身份与不可变数据类型相结合总是有点问题。在 PyPy 中摆脱所有这些极端情况的成本确实很高，而且 CPython 也会不时更改它们。当然，`id`在某些情况下，pickle 使可见是不幸的。CPython 中一些奇怪的例子`id`是，以下程序打印的两个数字是相同还是不同取决于 CPython 版本：
> 
> ```python
> print(id('a' * 100 + 'b'), id('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'))
> ```
> 
> 或者这个 cpython 行为的怪异之处：
> 
> ```python
> >>> def f(x): return x - 1 + 1 is x
> ... 
> >>> f(100)
> True
> >>> f(1000)
> False
> ```
> 
> （在 pypy 中，对于任意参数均返回 true。）



> right, I see. the JIT will constant-fold the `'' + 'ab'` to a constant string in the loop, which leads pickle to re-use the object reference instead of serializing the string again. this effect can be observed with this code too:
> 
> ```python
> options=['ab','ab','ab','ab','ab','ab','ab','ab'] * 10000
> temp = []
> for i in options:
>     print(id('' + i))
> ```
> 
> at some point, the id will become stable, because after the JIT has generated code for the loop the addition returns always the same string object. A lot of coincidences have to come together to cause this effect, eg if you put it into a function instead of running the code on the global level the constant-folding doesn't happen any more.
> 
> Because the unpickled list is the same, I don't consider this a real bug and more of a corner case.
> 
> @zzl261004 could you give some more details about why this was a problem for you, in the context of the larger program you were running?
> 
> Background thoughts: Combining identity with immutable data types is always a bit of a problem. It would be really costly to get rid of all of these corner cases in PyPy, and CPython changes them too, from time to time. It's of course unfortunate that pickle makes the `id` visible under some circumstances. Some examples for weirdness around `id` in CPython are whether the two numbers that the following program prints are the same or different depends on the CPython version:
> 
> ```python
> print(id('a' * 100 + 'b'), id('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab'))
> ```
> 
> or the weirdness of this cpython-behaviour:
> 
> ```python
> >>> def f(x): return x - 1 + 1 is x
> ... 
> >>> f(100)
> True
> >>> f(1000)
> False
> ```
> 
> (both returns true in pypy for arbitrary arguments.)


Thank you for your detailed response; I’ve learned a lot about PyPy and CPython from it. Combining identity with immutable data types often leads to issues.

**Comment by mattip** [comment] 2024-09-01 06:03
Closing this, please open a new issue if something still is problematic.

**Closed by mattip** 2024-09-01 06:03 UTC
