### ISSUE TITLE
why f6.py is no speedup but slower than f5.py in pypy, but it speedup 1 times in python 3.8

### ISSUE THREAD

**Issue by l1t1** [pypy/pypy#4820] opened 2024-01-02 06:27 UTC
f5.py
```
import time
t=time.time()
f=[i**5 for i in range(1,155)]
for a in range(1,150):
 for b in range(a+1,150):
  for c in range(b+1,150):
   for d in range(c+1,150):
    for e in range(d+1,150):
     if f[a]+f[b]+f[c]+f[d]<f[e]:break
     if f[a]+f[b]+f[c]+f[d]==f[e]:print(a,b,c,d,e,time.time()-t);exit()
```
f6.py
```
import time
t=time.time()
f=[i**5 for i in range(1,155)]
for a in range(1,150):
 for b in range(a+1,150):
  for c in range(b+1,150):
   for d in range(c+1,150):
    x=pow(f[a]+f[b]+f[c]+f[d],0.2)  #add 1
    for e in range(int(x)-1,150):      #add 2
     if f[a]+f[b]+f[c]+f[d]<f[e]:break
     if f[a]+f[b]+f[c]+f[d]==f[e]:print(a,b,c,d,e,time.time()-t);exit()
```
I run them in the way
```
D:\>python f5.py
26 83 109 132 143 42.441059589385986

D:\>python f6.py
26 83 109 132 143 20.630054235458374

-----------

D:\pypy311>pypy3 /f6.py
26 83 109 132 143 1.8761072158813477

D:\pypy311>pypy3 /f5.py
26 83 109 132 143 0.6500372886657715

D:\pypy311>pypy3
Python 3.10.13 (2998d86b1332e3e60a8bb1a37d06191cf31d550f, Dec 07 2023, 00:31:17)
[PyPy 7.3.14-alpha0 with MSC v.1929 64 bit (AMD64)] on win32
```

**Comment by l1t1** [comment] 2024-01-02 06:36
I noticed my post has been moved here just now.
https://github.com/pypy/pypy/issues/4042

**Comment by mattip** [comment] 2024-01-02 12:56
Duplicate of #4042, closing

**Closed by mattip** 2024-01-02 12:56 UTC
