### ISSUE TITLE
`python -m venv` from within tox env fails with PyPy 7.3.16 on Windows

### ISSUE THREAD

**Issue by jwodder** [pypy/pypy#4958] opened 2024-05-20 18:52 UTC
(I don't know whether this is tox's fault or PyPy's fault, so I'm reporting it in both places.  Tox issue: https://github.com/tox-dev/tox/issues/3284)

Given the following `tox.ini`:

```ini
[testenv]
skip_install = True
commands =
    python script.py
```

and the following `script.py`:

```python
import subprocess
import sys

subprocess.run([sys.executable, "-m", "venv", "venvdir"], check=True)
```

Running `tox` on Windows (specifically, GitHub Actions' `windows-latest` runner) using PyPy 7.3.16 (whether as Python 3.9.19 or Python 3.10.14) fails with:

```
Error: problem finding exes in ['libffi-8.dll', 'libpypy3.10-c.dll', 'pypy.exe', 'pypy3.10.exe', 'pypy3.10w.exe', 'pypy3.exe', 'pypyw.exe', 'python.exe', 'python3.10.exe', 'python3.exe', 'pythonw.exe']
Traceback (most recent call last):
 File "D:\a\test\test\script.py", line 4, in <module>
   subprocess.run([sys.executable, "-m", "venv", "venvdir"], check=True)
 File "C:\hostedtoolcache\windows\PyPy\3.10.14\x86\Lib\subprocess.py", line 526, in run
   raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\a\\test\\test\\.tox\\py\\Scripts\\python.EXE', '-m', 'venv', 'venvdir']' returned non-zero exit status 1.
```

Running the script outside of `tox` works, as do running `tox` with PyPy 7.3.15 and running `tox` with PyPy 7.3.16 on Ubuntu or macOS.

**Comment by mattip** [comment] 2024-05-21 07:15
That error comes from here, when creating the venv. https://github.com/pypy/pypy/blob/a9e95eeb370249ef008c437be8b8547b0d358215/lib-python/3/venv/__init__.py#L360. Lines 345-358 are only used in source builds (i.e. straight from translation/compilation, not from packaged PyPy like here), and are not relevant but now that I look at them they contain a different bug. I think the problem might be the name of the executable, with an upper case `EXE`. Could you verify that by modifying the PyPy used in the test with this change to enhance the error message?
```
--- a/lib-python/3/venv/__init__.py
+++ b/lib-python/3/venv/__init__.py
@@ -357,7 +357,7 @@ class EnvBuilder:
                     dst = os.path.join(binpath, exe)
                     copier(src, dst)
                 else:
-                    raise RuntimeError(f"problem finding exes in {suffixes}")
+                    raise RuntimeError(f"problem finding exe {exe} in {suffixes}")
 
             if sysconfig.is_python_build(True):
                 # copy init.tcl

```

**Comment by mattip** [comment] 2024-05-21 08:03
I can confirm the issue is due to the `EXE` in the suffix. Fixed in 84b4656435edebc9d7648f3508117d8a15baa5ed, and improved the error message in 627ea31bcaf9f2d25ca4fcac31bbe60422612127.

**Closed** 2024-08-20 09:14 UTC

**Comment by henryiii** [comment] 2024-09-03 15:10
Any temporary workarounds? All pypa/build's PyPy 3.9 and 3.10 tests are broken due to this (PyPy 3.8 is fine).

**Comment by mattip** [comment] 2024-09-03 16:36
I would suggest only testing pypy3.10, as that is the only version that is actively developed. The fix was released as part of PyPy v7.3.17 last week.

**Comment by webknjaz** [comment] 2024-12-16 03:33
@mattip thanks for the hint! I tried inspecting the change log and there's nothing that explicitly states that the support of 3.9 has been dropped. I haven't found any policies on what's supported / criteria for dropping. Is there a place that states which PyPy version dropped support for which Python. I kinda expected the change log to state something like "this version is the last to ship 3.9". So the only way to guess that something's not being developed seem to be such comments on GH and inferring this from the homepage (which doesn't specify when something was dropped).
Have you considered integrating with the EOL website and having something like https://endoflife.date/python presenting this info more clearly?

**Comment by hugovk** [comment] 2024-12-16 06:48
The last release announcement said:

> The keen-eyed will have noticed no mention of Python version 3.9 in the releases above. Typically we will maintain only one version of Python3, but due to PyPy3.9 support on conda-forge we maintained multiple versions from the first release of PyPy3.10 in PyPy v7.3.12 (Dec 2022). Conda-forge is sunsetting its PyPy support, which means we can drop PyPy3.9. 

https://pypy.org/posts/2024/08/pypy-v7317-release.html

Although a summary page would be useful: I only test the latest PyPy but I see a lot of projects testing PyPy3.8 or PyPy3.9.

**Comment by mattip** [comment] 2024-12-16 15:43
> I kinda expected the change log to state something like

When I release a version, I don't know what the next release will bring. 

> a summary page would be useful

This is a good idea. I will put it into a new issue.

**Comment by mattip** [comment] 2024-12-16 15:46
See #5154
