### ISSUE TITLE
InteractiveInterpreter.runsource fails on incomplete input

### ISSUE THREAD

**Issue by gitlab-importer** [pypy/pypy#4002] opened 2023-09-17 10:35 UTC
In Heptapod by @gpotter2 on Sep 17, 2023, 11:35

`InteractiveInterpreter.runsource()` is supposed to return `True` when the input is incomplete, as per the doc: https://docs.python.org/3/library/code.html#code.InteractiveInterpreter.runsource. This appears to have regressed in PyPy on 3.10.

**CPython 3.11.2:**
```python
>>> import code
>>> code.InteractiveInterpreter().runsource("a = \\")
True
```

**Python 3.9.17 (PyPy 7.3.12):**
```python
>>> import code
>>> code.InteractiveInterpreter().runsource("a = \\")
True
```

**Python 3.10.12 (PyPy 7.3.12):**
```python
>>> import code
>>> code.InteractiveInterpreter().runsource("a = \\")
  File "<input>", line 1
    a = \
        ^
SyntaxError: unexpected end of file (EOF) in multi-line statement
False
```

**Comment by mattip** [comment] 2024-01-04 06:05
Assuming this is something small, it might be nice to try to solve this, so I will mark it for 7.3.15

**Comment by gpotter2** [comment] 2024-01-04 15:27
Fun fact, cpython regressed in a very similar way in 3.12: `https://github.com/python/cpython/issues/113703`

**Comment by cfbolz** [comment] 2024-01-09 15:43
203cd17ca46c219432039191d51ca8fea03ed073 should have fixed this, let's try tomorrow.

**Comment by mattip** [comment] 2024-01-14 07:40
It worked for me on the nightly. Closing. Please reopen or open a new issue if the problem is not fixed.

**Closed by mattip** 2024-01-14 07:40 UTC
