### ISSUE TITLE
`while True: continue` fails to parse in 7.3.17

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [pypy/pypy#5090] opened 2024-10-28 21:02 UTC
The following code `a.py`:
```py
print("Hello, World!")
while True: continue
```
causes `pypy3 a.py` to hang, without first printing `Hello, World!`. Somehow, the code causes the internal parser to hang.

All of the following work as expected, so it must be something very specific to the `while True: continue` being a single line.
```py
print("Hello, World!")
while True:
    continue
```
```py
print("Hello, World!")
while False: continue
```
```py
print("Hello, World!")
while True: pass
```

Version (the current latest on Archlinux)
```
pypy3 --version
Python 3.10.14 (39dc8d3c85a7, Aug 30 2024, 08:27:45)
[PyPy 7.3.17 with GCC 14.2.1 20240805]
```
The same error seems to be present in `7.3.16` and `7.3.15` as well.

**Comment by mattip** [comment] 2024-10-29 05:43
Can reproduce on ubuntu linux with 3.10 HEAD. Not only does it hang, it is not responsive to Ctrl-C (unlike CPython)

**Comment by mattip** [comment] 2024-10-29 06:14
This fails to open /tmp/stam, but of course it does if commenting out the `while True: continue`
```
import sys
fid = open("/tmp/stam", "w")
print("Hello, World!", file=fid)
fid.close()
while True: continue
```

**Comment by mattip** [comment] 2024-10-29 06:36
It seems the problem is in the parser, it does not even need to run the code. Importing a file with this hangs:
```
def g():
    print("Hello, World!")
    while True: continue
```

**Comment by cfbolz** [comment] 2024-10-29 09:44
should be fixed by the above commit, let's check tomorrow

**Comment by mattip** [comment] 2024-10-30 15:24
Closing. Thanks for the report and the quick fix.

**Closed by mattip** 2024-10-30 15:24 UTC

**Comment by arigo** [comment] 2024-11-08 04:16
If we parse bytecode that ends up with two or more JUMP_ABSOLUTE going to each other, wouldn't it be caught into an infinite loop as well?  Shouldn't it be fixed more conservatively, e.g. by enforcing a maximum number of repeated iterations in that loop?
