### ISSUE TITLE
The socket to MySQL server remains open on the client side even socket.close() was called

### ISSUE THREAD

**Issue by Yevhenii-Yatchenko** [pypy/pypy#5020] opened 2024-09-02 17:48 UTC
Dears,

I've noticed a different behavior on CPython and PyPy while using pymysql.

Python and pymysql versions:
```
> pypy3.9
Python 3.9.16 (0c1db6dfd716, Jul 17 2024, 14:40:59)
[PyPy 7.3.11 with GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import pymysql
>>>> pymysql.__version__
'1.4.6'
>>>> 
```

```
> python3.9
Python 3.9.19 (main, May 30 2024, 06:55:59) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-22.0.1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymysql
>>> pymysql.__version__
'1.4.6'
>>> pymysql.__version__
KeyboardInterrupt
>>>
```

STR
1. Create an instance of pymysql connection and cursor,
2. Start infinitely executing ping (with reconnect flag) + some query to a MySQL DB.
3. Check what sockets are open from the tested interpreter (must be a single socket)
```
## for pypy3.9
while true; do sudo netstat -anp | grep 3306 | grep pypy3.9; echo '---'; sleep 1; done;
## for python3.9
while true; do sudo netstat -anp | grep 3306 | grep python3.9; echo '---'; sleep 1; done;
```
4. Emulate connection failure between the client and the server:
```
# start the outage
sudo iptables -I OUTPUT 1 -p tcp --sport 3306 -j DROP
# stop the outage
sudo iptables -D OUTPUT 1
```
5. Check what is shown in the terminal run on stage 3. 
- PyPy3.9: we see two opened sockets (the new one after the reconnection + the dead one) in the ESTABLISHED state
- CPython3.9: there is only one socket in the ESTABLISHED state

So, on CPython the dead socket is instantly closed right after the network outage. On the PyPy - the client socket is alive for a long time (it looks like for TCP keepalives time) or infinitely.

Attaching a script I used to reproduce it and reports gathered for PyPy3.9 and CPython3.9 interpreters.
The problem appears in real, non-laboratory conditions when the connectivity between the client and the server is unstable.

[cpython_report.txt](https://github.com/user-attachments/files/16840252/cpython_report.txt)
[pypy_report.txt](https://github.com/user-attachments/files/16840254/pypy_report.txt)
[python_script.txt](https://github.com/user-attachments/files/16840260/python_script.txt)

Please let me know if additional info is required.

**Comment by Yevhenii-Yatchenko** [comment] 2024-09-02 17:51
An interesting fact is that "socket.close()" is called for the dead socket (I've decorated the method to ensure this), and "socket.__repr__()" shows that it is dead, but OS thinks it is alive (netstat shows that, please see the reports)

**Comment by cfbolz** [comment] 2024-09-03 10:35
yep, can reproduce this. I'm looking into it.

**Comment by cfbolz** [comment] 2024-09-03 11:09
it's a bug in `pymysql`. In their `_force_close` implementation they don't close the `_rfile` attribute. This will keep the underlying OS socket open until the `socket.SockeIO` is garbage collected. On CPython this happens immediately due to reference counting, on pypy only at the end of the next major GC cycle.

here's the code that I used to investigate this problem:

```python
import sys

import pymysql
from time import sleep
import os

execname = os.path.basename(sys.executable)

db_config = {
    'host': 'localhost',
    'user': 'rob',
    'password': '123456',
    'connect_timeout': 1,
    'read_timeout': 1,
    'write_timeout': 1,
}

def netstat():
    os.system(f"netstat -anp 2>/dev/null | grep 3306 | grep {os.getpid()}")

connection = pymysql.connect(**db_config)

print(f"{connection=} {connection._sock=} {connection._rfile=}")
netstat()
connection._force_close()
print(f"after _force_close {connection=} {connection._sock=} {connection._rfile=}")
netstat()

import gc
gc.collect()
print("after collect")
netstat()

print("_" * 60)
print("now let's keep the the socket alive ourselves")

connection = pymysql.connect(**db_config)
sock = connection._sock
rfile = connection._rfile

print(f"{connection=} {connection._sock=} {connection._rfile=}")
netstat()
connection._force_close()
print(f"after _force_close {connection=} {connection._sock=} {connection._rfile=}")
print(f"{sock=} {rfile=}")
netstat()

import gc
gc.collect()
print("after collect")
netstat()

rfile.close()
sock.close()
print("after explicit close")
netstat()

print("_" * 60)
print("let's fix the bug")

connection = pymysql.connect(**db_config)
# keep sock and rfile alive to simulate the bug on cpy too
sock = connection._sock
rfile = connection._rfile

def force_close(self, *args, **kwargs):
    print("Modified force close called")
    if self._rfile:
        self._rfile.close()
    return original_force_close(self, *args, **kwargs)

# patch the class
original_force_close = type(connection)._force_close
type(connection)._force_close = force_close

print(f"{connection=} {connection._sock=} {connection._rfile=}")
netstat()
connection._force_close()
print(f"after _force_close {connection=} {connection._sock=} {connection._rfile=}")
print(f"{sock=} {rfile=}")
netstat()
```

I'll file a pymysql bug.

**Comment by cfbolz** [comment] 2024-09-05 07:23
PyMySQL merged my PR to fix the problem, I'm closing this bug.

**Closed by cfbolz** 2024-09-05 07:23 UTC
